< {%
    const code = "8DLycecqoFl_YTmn5oUzbVu0Hnd_q1Rt261p5qYmVcsbd0ttH2iNK-OsBknGmq5J6R14tqwkvhPbNyezWM7fO_HkDK7BqEL9v5nmblNWzOiPTN6APEWVEv_s5pQHH_xZ"
    const redirect_uri = "http://127.0.0.1:3000/authorizationCallback"
    const auth = Window.btoa('bookshare-web-client:bookshare-web-client-secret') ;
    request.variables.set("auth", auth);
    request.variables.set("code", code);
    request.variables.set("redirect_uri", redirect_uri);
%}
POST {{url}}/oauth2/token
Content-Type: application/x-www-form-urlencoded
Authorization: Basic {{auth}}

code = {{code}} &
grant_type = authorization_code &
redirect_uri = {{redirect_uri}} &
code_verifier = secret_challenge

> {%
    client.global.set("access_token", response.body["access_token"])
%}
